
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_DiffieHellman(object):
    def setupUi(self, Form_DiffieHellman):
        Form_DiffieHellman.setObjectName("Diffie Hellman")
        Form_DiffieHellman.resize(714, 459)
        self.centralwidget = QtWidgets.QWidget(Form_DiffieHellman)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(340, 40, 20, 421))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(130, 10, 54, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(530, 10, 54, 17))
        self.label_2.setObjectName("label_2")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(250, 10, 200, 17))
        self.label_15.setObjectName("label_15")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 54, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 100, 54, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 40, 301, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 70, 301, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 100, 301, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(30, 140, 101, 25))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(230, 220, 101, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(30, 180, 301, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 180, 54, 17))
        self.label_6.setObjectName("label_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(230, 140, 101, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(390, 40, 301, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(370, 40, 54, 17))
        self.label_7.setObjectName("label_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(390, 80, 101, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(370, 120, 54, 17))
        self.label_8.setObjectName("label_8")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(390, 120, 301, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(370, 150, 54, 17))
        self.label_9.setObjectName("label_9")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(390, 150, 301, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 180, 54, 17))
        self.label_10.setObjectName("label_10")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(390, 180, 301, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(390, 260, 301, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(370, 260, 54, 17))
        self.label_11.setObjectName("label_11")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(390, 220, 101, 25))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(590, 300, 101, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(30, 260, 301, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 260, 54, 17))
        self.label_12.setObjectName("label_12")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 300, 141, 25))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(390, 300, 141, 25))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(30, 370, 301, 25))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(10, 340, 91, 17))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(360, 340, 91, 17))
        self.label_14.setObjectName("label_14")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(380, 370, 301, 25))
        self.lineEdit_12.setObjectName("lineEdit_12")
        Form_DiffieHellman.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_DiffieHellman)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 714, 22))
        self.menubar.setObjectName("menubar")
        self.action = QtWidgets.QAction(self.menubar)
        self.action.setObjectName("action")
        Form_DiffieHellman.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_DiffieHellman)
        self.statusbar.setObjectName("statusbar")
        Form_DiffieHellman.setStatusBar(self.statusbar)


        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.action_2 = QtWidgets.QAction(self.menu)
        self.action_2.setObjectName("action_2")
        self.menu.addAction(self.action_2)
        self.menubar.addMenu(self.menu)
        self.menubar.addAction(self.action)

        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_13.setText("50")
        self.lineEdit_13.hide()

        self.retranslateUi(Form_DiffieHellman)
        QtCore.QMetaObject.connectSlotsByName(Form_DiffieHellman)

    def retranslateUi(self, Form_DiffieHellman):
        _translate = QtCore.QCoreApplication.translate
        Form_DiffieHellman.setWindowTitle(_translate("Form_DiffieHellman", "Form_DiffieHellman"))
        self.label.setText(_translate("Form_DiffieHellman", "Alice"))
        self.label_2.setText(_translate("Form_DiffieHellman", "Bob"))
        self.label_3.setText(_translate("Form_DiffieHellman", "a:"))
        self.label_4.setText(_translate("Form_DiffieHellman", "g:"))
        self.label_5.setText(_translate("Form_DiffieHellman", "p:"))
        self.pushButton.setText(_translate("Form_DiffieHellman", "Сгенерировать"))
        self.pushButton_2.setText(_translate("Form_DiffieHellman", "Отправить"))
        self.label_6.setText(_translate("Form_DiffieHellman", "A:"))
        self.pushButton_3.setText(_translate("Form_DiffieHellman", "Рассчитать"))
        self.label_7.setText(_translate("Form_DiffieHellman", "b:"))
        self.pushButton_4.setText(_translate("Form_DiffieHellman", "Сгенерировать"))
        self.label_8.setText(_translate("Form_DiffieHellman", "g:"))
        self.label_9.setText(_translate("Form_DiffieHellman", "p:"))
        self.label_10.setText(_translate("Form_DiffieHellman", "A:"))
        self.label_11.setText(_translate("Form_DiffieHellman", "B:"))
        self.pushButton_5.setText(_translate("Form_DiffieHellman", "Рассчитать"))
        self.pushButton_6.setText(_translate("Form_DiffieHellman", "Отправить"))
        self.label_12.setText(_translate("Form_DiffieHellman", "B:"))
        self.pushButton_7.setText(_translate("Form_DiffieHellman", "Рассчитать ключ"))
        self.pushButton_8.setText(_translate("Form_DiffieHellman", "Рассчитать ключ"))
        self.label_13.setText(_translate("Form_DiffieHellman", "Общий ключ:"))
        self.label_14.setText(_translate("Form_DiffieHellman", "Общий ключ:"))
        self.action.setText(_translate("Form_DiffieHellman", "Назад"))
        self.label_15.setText(_translate("Form_DiffieHellman", "Длина чисел 50 символов."))
        self.menu.setTitle(_translate("Form_DiffieHellman", "Числа"))
        self.action_2.setText(_translate("Form_DiffieHellman", "Задать длину чисел"))

