# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'digital_signature_elgamal_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_DigSignElGamal(object):
    def setupUi(self, Form_DigSignElGamal):
        Form_DigSignElGamal.setObjectName("Form_DigSignElGamal")
        Form_DigSignElGamal.resize(680, 430)
        Form_DigSignElGamal.setMinimumSize(QtCore.QSize(680, 430))
        Form_DigSignElGamal.setMaximumSize(QtCore.QSize(680, 430))
        self.centralwidget = QtWidgets.QWidget(Form_DigSignElGamal)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(330, 30, 20, 351))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 321, 61))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 54, 17))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(3, 130, 54, 17))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(3, 160, 54, 17))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(20, 130, 311, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setReadOnly(True)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(20, 160, 311, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setReadOnly(True)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 100, 171, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(3, 210, 54, 17))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(20, 210, 311, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setReadOnly(True)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(3, 260, 54, 17))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(20, 260, 311, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setReadOnly(True)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(3, 290, 121, 17))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(10, 310, 321, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_5.setReadOnly(True)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 350, 231, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(210, 100, 121, 25))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 240, 191, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 190, 191, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(350, 10, 54, 17))
        self.label_9.setObjectName("label_9")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(350, 30, 321, 61))
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setReadOnly(True)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(357, 120, 311, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_6.setReadOnly(True)
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(350, 100, 121, 17))
        self.label_10.setObjectName("label_10")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(350, 150, 191, 31))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(343, 190, 54, 17))
        self.label_11.setObjectName("label_11")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(360, 190, 311, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_7.setReadOnly(True)
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(343, 220, 54, 17))
        self.label_12.setObjectName("label_12")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(360, 220, 311, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_8.setReadOnly(True)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(343, 250, 54, 17))
        self.label_13.setObjectName("label_13")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(360, 250, 311, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_9.setReadOnly(True)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(410, 280, 201, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(353, 330, 121, 17))
        self.label_14.setObjectName("label_14")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(360, 350, 311, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_10.setReadOnly(True)
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(500, 10, 181, 17))
        self.label_15.setObjectName("label_15")
        Form_DigSignElGamal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_DigSignElGamal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 680, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        Form_DigSignElGamal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_DigSignElGamal)
        self.statusbar.setObjectName("statusbar")
        Form_DigSignElGamal.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Form_DigSignElGamal)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Form_DigSignElGamal)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(Form_DigSignElGamal)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(Form_DigSignElGamal)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(Form_DigSignElGamal)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.action_5)

        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setObjectName("label_16")
        self.label_16.hide()

        self.retranslateUi(Form_DigSignElGamal)
        QtCore.QMetaObject.connectSlotsByName(Form_DigSignElGamal)

    def retranslateUi(self, Form_DigSignElGamal):
        _translate = QtCore.QCoreApplication.translate
        Form_DigSignElGamal.setWindowTitle(_translate("Form_DigSignElGamal", "Form_DigSignElGamal"))
        self.label.setText(_translate("Form_DigSignElGamal", "Данные:"))
        self.label_2.setText(_translate("Form_DigSignElGamal", "p:"))
        self.label_3.setText(_translate("Form_DigSignElGamal", "g:"))
        self.pushButton_2.setText(_translate("Form_DigSignElGamal", "Сгенерировать подпись"))
        self.label_4.setText(_translate("Form_DigSignElGamal", "x:"))
        self.label_5.setText(_translate("Form_DigSignElGamal", "y:"))
        self.label_6.setText(_translate("Form_DigSignElGamal", "Подпись:"))
        self.pushButton_3.setText(_translate("Form_DigSignElGamal", "Отправить сообщение с подписью"))
        self.comboBox.setItemText(0, _translate("Form_DigSignElGamal", "md5"))
        self.comboBox.setItemText(1, _translate("Form_DigSignElGamal", "sha1"))
        self.label_7.setText(_translate("Form_DigSignElGamal", "Открытый ключ:"))
        self.label_8.setText(_translate("Form_DigSignElGamal", "Закрытый ключ:"))
        self.label_9.setText(_translate("Form_DigSignElGamal", "Данные:"))
        self.label_10.setText(_translate("Form_DigSignElGamal", "Подпись:"))
        self.pushButton_4.setText(_translate("Form_DigSignElGamal", "Получить ключ и общие числа"))
        self.label_11.setText(_translate("Form_DigSignElGamal", "p:"))
        self.label_12.setText(_translate("Form_DigSignElGamal", "g:"))
        self.label_13.setText(_translate("Form_DigSignElGamal", "y:"))
        self.pushButton.setText(_translate("Form_DigSignElGamal", "Проверить подпись"))
        self.label_14.setText(_translate("Form_DigSignElGamal", "Результат:"))
        self.label_15.setText(_translate("Form_DigSignElGamal", "Длина ключей 50 символов."))
        self.label_16.setText(_translate("Form_DigSignElGamal", "50"))
        self.menu.setTitle(_translate("Form_DigSignElGamal", "Файл"))
        self.menu_2.setTitle(_translate("Form_DigSignElGamal", "Ключи"))
        self.action.setText(_translate("Form_DigSignElGamal", "Загрузить файл"))
        self.action_2.setText(_translate("Form_DigSignElGamal", "Загрузить подпись и ключи"))
        self.action_3.setText(_translate("Form_DigSignElGamal", "Сохранить подпись и ключи"))
        self.action_4.setText(_translate("Form_DigSignElGamal", "Задать длину ключей"))
        self.action_5.setText(_translate("Form_DigSignElGamal", "Назад"))
