# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dsa_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_DSA(object):
    def setupUi(self, Form_DSA):
        Form_DSA.setObjectName("Form_DSA")
        Form_DSA.resize(724, 590)
        Form_DSA.setMinimumSize(QtCore.QSize(724, 590))
        Form_DSA.setMaximumSize(QtCore.QSize(724, 590))
        self.centralwidget = QtWidgets.QWidget(Form_DSA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 110, 54, 17))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 130, 701, 51))
        self.textEdit.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit.setObjectName("textEdit")
        self.textEdit.setReadOnly(True)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 180, 54, 17))
        self.label_2.setObjectName("label_2")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 200, 701, 21))
        self.textEdit_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.textEdit_2.setObjectName("textEdit_2")
        self.textEdit_2.setReadOnly(True)
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 240, 701, 31))
        self.textEdit_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.textEdit_3.setObjectName("textEdit_3")
        self.textEdit_3.setReadOnly(True)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 220, 54, 17))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 280, 221, 41))
        self.pushButton.setObjectName("pushButton")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(350, 0, 20, 111))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 10, 54, 17))
        self.label_4.setObjectName("label_4")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 30, 341, 70))
        self.textEdit_4.setObjectName("textEdit_4")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 280, 181, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 340, 141, 17))
        self.label_5.setObjectName("label_5")
        self.textEdit_5 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_5.setGeometry(QtCore.QRect(10, 360, 341, 31))
        self.textEdit_5.setObjectName("textEdit_5")
        self.textEdit_5.setReadOnly(True)
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 390, 141, 17))
        self.label_6.setObjectName("label_6")
        self.textEdit_6 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_6.setGeometry(QtCore.QRect(10, 410, 341, 31))
        self.textEdit_6.setObjectName("textEdit_6")
        self.textEdit_6.setReadOnly(True)
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 450, 151, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 480, 141, 17))
        self.label_7.setObjectName("label_7")
        self.textEdit_7 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_7.setGeometry(QtCore.QRect(10, 500, 341, 41))
        self.textEdit_7.setObjectName("textEdit_7")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(200, 450, 151, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(370, 10, 54, 17))
        self.label_8.setObjectName("label_8")
        self.textEdit_8 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_8.setGeometry(QtCore.QRect(370, 30, 341, 70))
        self.textEdit_8.setObjectName("textEdit_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(370, 340, 141, 17))
        self.label_9.setObjectName("label_9")
        self.textEdit_9 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_9.setGeometry(QtCore.QRect(370, 360, 341, 41))
        self.textEdit_9.setObjectName("textEdit_9")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(510, 280, 201, 41))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(370, 410, 141, 17))
        self.label_10.setObjectName("label_10")
        self.textEdit_10 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_10.setGeometry(QtCore.QRect(370, 430, 341, 31))
        self.textEdit_10.setObjectName("textEdit_10")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 470, 151, 25))
        self.pushButton_6.setObjectName("pushButton_6")
        self.textEdit_11 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_11.setGeometry(QtCore.QRect(370, 510, 341, 31))
        self.textEdit_11.setObjectName("textEdit_11")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(370, 490, 141, 17))
        self.label_11.setObjectName("label_11")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(350, 330, 20, 221))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(500, 110, 291, 17))
        self.label_12.setObjectName("label_12")
        self.label_12.hide()
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(500, 180, 291, 17))
        self.label_13.setObjectName("label_13")
        self.label_13.hide()
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(500, 220, 291, 17))
        self.label_14.setObjectName("label_14")
        self.label_14.hide()
        Form_DSA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_DSA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        Form_DSA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_DSA)
        self.statusbar.setObjectName("statusbar")
        Form_DSA.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Form_DSA)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Form_DSA)
        self.action_3 = QtWidgets.QAction(Form_DSA)
        self.action_4 = QtWidgets.QAction(Form_DSA)
        self.action_5 = QtWidgets.QAction(Form_DSA)
        self.action_6 = QtWidgets.QAction(Form_DSA)
        self.menu.addAction(self.action)
        self.menu_2.addAction(self.action_2)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.action_6)

        self.retranslateUi(Form_DSA)
        QtCore.QMetaObject.connectSlotsByName(Form_DSA)

    def retranslateUi(self, Form_DSA):
        _translate = QtCore.QCoreApplication.translate
        Form_DSA.setWindowTitle(_translate("Form_DSA", "DSA"))
        self.label.setText(_translate("Form_DSA", "p:"))
        self.label_2.setText(_translate("Form_DSA", "q:"))
        self.label_3.setText(_translate("Form_DSA", "g (a):"))
        self.pushButton.setText(_translate("Form_DSA", "Сгенерировать общие параметры"))
        self.label_4.setText(_translate("Form_DSA", "Данные:"))
        self.pushButton_2.setText(_translate("Form_DSA", "Сгенерировать ключи"))
        self.label_5.setText(_translate("Form_DSA", "Открытый ключ:"))
        self.label_6.setText(_translate("Form_DSA", "Закрытый ключ:"))
        self.pushButton_3.setText(_translate("Form_DSA", "Сгенерировать подпись"))
        self.label_7.setText(_translate("Form_DSA", "Подпись:"))
        self.pushButton_4.setText(_translate("Form_DSA", "Отправить данные "))
        self.label_8.setText(_translate("Form_DSA", "Данные:"))
        self.label_9.setText(_translate("Form_DSA", "Подпись:"))
        self.pushButton_5.setText(_translate("Form_DSA", "Получить открытый ключ"))
        self.label_10.setText(_translate("Form_DSA", "Открытый ключ:"))
        self.pushButton_6.setText(_translate("Form_DSA", "Проверить подпись"))
        self.label_11.setText(_translate("Form_DSA", "Результат:"))
        self.label_12.setText(_translate("Form_DSA", "Выполняется генерация числа"))
        self.label_13.setText(_translate("Form_DSA", "Выполняется генерация числа"))
        self.label_14.setText(_translate("Form_DSA", "Выполняется генерация числа"))
        self.menu.setTitle(_translate("Form_DSA", "Файл"))
        self.menu_2.setTitle(_translate("Form_DSA", "Ключи"))
        self.menu_3.setTitle(_translate("Form_DSA", "Назад"))
        self.action.setText(_translate("Form_DSA", "Загрузить файл"))
        self.action_2.setText(_translate("Form_DSA", "Сохранить числа и ключи"))
        self.action_3.setText(_translate("Form_DSA", "Сохранить подпись"))
        self.action_4.setText(_translate("Form_DSA", "Загрузить числа и ключи"))
        self.action_5.setText(_translate("Form_DSA", "Загрузить подпись"))
        self.action_6.setText(_translate("Form_DSA", "Назад"))

