from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_ElGamal(object):
    def setupUi(self, Form_ElGamal):
        Form_ElGamal.setObjectName("Form_ElGamal")
        Form_ElGamal.resize(611, 506)
        Form_ElGamal.setMinimumSize(QtCore.QSize(611, 506))
        Form_ElGamal.setMaximumSize(QtCore.QSize(611, 506))
        self.centralwidget = QtWidgets.QWidget(Form_ElGamal)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 17))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 591, 70))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 54, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(40, 110, 561, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(40, 140, 561, 25))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 54, 17))
        self.label_3.setObjectName("label_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 170, 261, 31))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(340, 170, 261, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 210, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 240, 54, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 54, 17))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 300, 54, 17))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 330, 54, 17))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(310, 210, 54, 17))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(310, 240, 54, 17))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(310, 270, 54, 17))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(10, 360, 171, 17))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(410, 10, 171, 17))
        self.label_13.setObjectName("label_13")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 380, 591, 70))
        self.textEdit_2.setObjectName("textEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(40, 210, 261, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(40, 240, 261, 25))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(40, 270, 261, 25))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(40, 300, 261, 25))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(40, 330, 261, 25))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(340, 210, 261, 25))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(340, 240, 261, 25))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(340, 270, 261, 25))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_3.setReadOnly(True)
        self.lineEdit_4.setReadOnly(True)
        self.lineEdit_5.setReadOnly(True)
        self.lineEdit_6.setReadOnly(True)
        self.lineEdit_7.setReadOnly(True)
        self.lineEdit_8.setReadOnly(True)
        self.lineEdit_9.setReadOnly(True)
        self.lineEdit_10.setReadOnly(True)

        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_11.hide()
        self.lineEdit_11.setText("50")
        Form_ElGamal.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_ElGamal)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 611, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")

        Form_ElGamal.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_ElGamal)
        self.statusbar.setObjectName("statusbar")
        Form_ElGamal.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Form_ElGamal)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Form_ElGamal)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(Form_ElGamal)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(Form_ElGamal)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(Form_ElGamal)
        self.action_5.setObjectName("action_5")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.action_5)

        self.retranslateUi(Form_ElGamal)
        QtCore.QMetaObject.connectSlotsByName(Form_ElGamal)

    def retranslateUi(self, Form_ElGamal):
        _translate = QtCore.QCoreApplication.translate
        Form_ElGamal.setWindowTitle(_translate("Form_ElGamal", "ElGamal"))
        self.label.setText(_translate("Form_ElGamal", "Сообщение:"))
        self.label_2.setText(_translate("Form_ElGamal", "p:"))
        self.label_3.setText(_translate("Form_ElGamal", "g:"))
        self.pushButton.setText(_translate("Form_ElGamal", "Сгенерировать"))
        self.pushButton_2.setText(_translate("Form_ElGamal", "Отправить сообщение"))
        self.label_4.setText(_translate("Form_ElGamal", "с(a):"))
        self.label_5.setText(_translate("Form_ElGamal", "d(a):"))
        self.label_6.setText(_translate("Form_ElGamal", "k:"))
        self.label_7.setText(_translate("Form_ElGamal", "r:"))
        self.label_8.setText(_translate("Form_ElGamal", "e:"))
        self.label_9.setText(_translate("Form_ElGamal", "с(b):"))
        self.label_10.setText(_translate("Form_ElGamal", "d(b):"))
        self.label_11.setText(_translate("Form_ElGamal", "m\':"))
        self.label_12.setText(_translate("Form_ElGamal", "Полученное сообщение:"))
        self.label_13.setText(_translate("Form_ElGamal", "Длина ключей 50 символов."))
        self.menu.setTitle(_translate("Form_ElGamal", "Файл"))
        self.menu_2.setTitle(_translate("Form_ElGamal", "Ключи"))
        self.action.setText(_translate("Form_ElGamal", "Загрузить файл"))
        self.action_2.setText(_translate("Form_ElGamal", "Загрузить данные"))
        self.action_3.setText(_translate("Form_ElGamal", "Сохранить как файл"))
        self.action_4.setText(_translate("Form_ElGamal", "Задать длину ключей"))
        self.action_5.setText(_translate("Form_ElGamal", "Назад"))
