from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Hash(object):
    def setupUi(self, Form_Hash):
        Form_Hash.setObjectName("Form_Hash")
        Form_Hash.resize(608, 365)
        self.centralwidget = QtWidgets.QWidget(Form_Hash)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 591, 181))
        self.textEdit.setObjectName("textEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 220, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(10, 290, 591, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setReadOnly(True)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.hide()
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 270, 191, 17))
        self.label_2.setObjectName("label_2")
        Form_Hash.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_Hash)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 608, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.action_4 = QtWidgets.QAction(Form_Hash)
        self.action_4.setObjectName("action_4")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.hide()
        Form_Hash.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_Hash)
        self.statusbar.setObjectName("statusbar")
        Form_Hash.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Form_Hash)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Form_Hash)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(Form_Hash)
        self.action_3.setObjectName("action_3")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_3)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.action_4)

        self.retranslateUi(Form_Hash)
        QtCore.QMetaObject.connectSlotsByName(Form_Hash)

    def retranslateUi(self, Form_Hash):
        _translate = QtCore.QCoreApplication.translate
        Form_Hash.setWindowTitle(_translate("Form_Hash", "Form_Hash"))
        self.label.setText(_translate("Form_Hash", "Данные для хэширования:"))
        self.pushButton.setText(_translate("Form_Hash", "Выполнить"))
        self.label_2.setText(_translate("Form_Hash", "Результат:"))
        self.menu.setTitle(_translate("Form_Hash", "Файл"))
        self.lineEdit_2.setText("False")
        self.action.setText(_translate("Form_Hash", "Загрузить из файла"))
        self.action_2.setText(_translate("Form_Hash", "Загрузить файл"))
        self.action_3.setText(_translate("Form_Hash", "Сохранить "))
        self.action_4.setText(_translate("Form_Hash", "Назад "))
