# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rsa_window.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_RSA(object):
    def setupUi(self, Form_RSA):
        Form_RSA.setObjectName("Form_RSA")
        Form_RSA.resize(600, 500)
        Form_RSA.setMinimumSize(QtCore.QSize(600, 500))
        Form_RSA.setMaximumSize(QtCore.QSize(600, 500))
        self.centralwidget = QtWidgets.QWidget(Form_RSA)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 17))
        self.label.setObjectName("label")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 30, 571, 91))
        self.textEdit.setObjectName("textEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 130, 181, 17))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 150, 551, 25))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(30, 180, 551, 25))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 150, 54, 17))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 54, 17))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 210, 131, 17))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 230, 54, 17))
        self.label_6.setObjectName("label_6")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(30, 230, 551, 25))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 270, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, 340, 191, 17))
        self.label_7.setObjectName("label_7")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(10, 360, 571, 91))
        self.textEdit_2.setObjectName("textEdit_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(210, 270, 171, 61))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(410, 270, 171, 61))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(410, 130, 171, 17))
        self.label_8.setObjectName("label_8")
        Form_RSA.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Form_RSA)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 22))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        Form_RSA.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Form_RSA)
        self.statusbar.setObjectName("statusbar")
        Form_RSA.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(Form_RSA)
        self.action.setObjectName("action")
        self.action_2 = QtWidgets.QAction(Form_RSA)
        self.action_2.setObjectName("action_2")
        self.action_3 = QtWidgets.QAction(Form_RSA)
        self.action_3.setObjectName("action_3")
        self.action_4 = QtWidgets.QAction(Form_RSA)
        self.action_4.setObjectName("action_4")
        self.action_5 = QtWidgets.QAction(Form_RSA)
        self.action_5.setObjectName("action_5")
        self.action_6 = QtWidgets.QAction(Form_RSA)
        self.action_6.setObjectName("action_6")
        self.action_7 = QtWidgets.QAction(Form_RSA)
        self.action_7.setObjectName("action_7")
        self.menu.addAction(self.action)
        self.menu.addAction(self.action_2)
        self.menu.addAction(self.action_7)
        self.menu_2.addAction(self.action_3)
        self.menu_2.addAction(self.action_4)
        self.menu_2.addAction(self.action_5)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.action_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(0, 0, 0, 0))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.hide()
        self.lineEdit_4.setText("50")

        self.retranslateUi(Form_RSA)
        QtCore.QMetaObject.connectSlotsByName(Form_RSA)

    def retranslateUi(self, Form_RSA):
        _translate = QtCore.QCoreApplication.translate
        Form_RSA.setWindowTitle(_translate("Form_RSA", "RSA"))
        self.label.setText(_translate("Form_RSA", "Исходные данные: "))
        self.label_2.setText(_translate("Form_RSA", "Пара открытых ключей:"))
        self.label_3.setText(_translate("Form_RSA", "e: "))
        self.label_4.setText(_translate("Form_RSA", "n:"))
        self.label_5.setText(_translate("Form_RSA", "Закрытый ключ:"))
        self.label_6.setText(_translate("Form_RSA", "d: "))
        self.pushButton.setText(_translate("Form_RSA", "Сгенерировать ключи"))
        self.label_7.setText(_translate("Form_RSA", "Результат"))
        self.pushButton_2.setText(_translate("Form_RSA", "Шифровать"))
        self.pushButton_3.setText(_translate("Form_RSA", "Расшифровать"))
        self.label_8.setText(_translate("Form_RSA", "Длина ключей 50 символов"))
        self.menu.setTitle(_translate("Form_RSA", "Файл"))
        self.menu_2.setTitle(_translate("Form_RSA", "Ключи"))
        self.action.setText(_translate("Form_RSA", "Загрузить файл"))
        self.action_2.setText(_translate("Form_RSA", "Загрузить данные"))
        self.action_7.setText(_translate("Form_RSA", "Сохранить"))
        self.action_3.setText(_translate("Form_RSA", "Загрузить"))
        self.action_4.setText(_translate("Form_RSA", "Сохранить"))
        self.action_5.setText(_translate("Form_RSA", "Задать длину ключей"))
        self.action_6.setText(_translate("Form_RSA", "Назад"))

